name: Build Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17 (For Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle (Forcing Java 8 Compatibility)
        run: gradle clean build -PsourceCompatibility=1.8 -PtargetCompatibility=1.8

      - name: Save Compiled Jar
        uses: actions/upload-artifact@v4
        with:
          name: compiled-plugin
          path: '**/build/libs/*.jar'
